# Remi CB copied from https://b.corp.google.com/issues/371959026
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - Dockerfile
    id: Build docker file.
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push to Artifact Repository
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    # All configs for `gcloud run deploy` are here: https://cloud.google.com/sdk/gcloud/reference/run/deploy
    args:
      - run
      - deploy
      # - services
      # - update
      - $_SERVICE_NAME
      - '--platform=managed'
      #- '--port=80'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
#      - >-
 #       --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,php-amarcord-github-user=$_GITHUB_USER,devfest-city:$_DEVFEST_CITY
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
# non va col services..
      - '--allow-unauthenticated'
    # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
    env:
    # copying RAILS_ENV approach.
    - PHP_ENV=development
    - PORT=80
    # - 'PROJECT_ID=$PROJECT_ID'
    # - 'PROJECT_NUMBER=$PROJECT_NUMBER'
    # - 'REV=$REVISION_ID'
    id: Deploy to DEV version
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DEPLOY_REGION: europe-west8
  _AR_HOSTNAME: europe-west8-docker.pkg.dev
  _PLATFORM: managed
#  _TRIGGER_ID: 9891957f-78d9-4931-a993-300127dafa7e
  _SERVICE_NAME: php-amarcord-cb # -dev
  _EXECUTION_ENVIRONMENT: 'rgc/cloudbuild'
  _GITHUB_USER: palladius
  _DEVFEST_CITY: modena
tags:
  - gcp-cloud-build-deploy-cloud-run
  - php-amarcord
  - ricc-ne-sa-a-tronchi
  # - gcp-cloud-build-deploy-cloud-run-managed
  # - zapiekanka
  # - gegonos


### ERRORs
#Step #2 - "Deploy to DEV version": ERROR: (gcloud.run.services.update) PERMISSION_DENIED: Permission 'run.services.get' denied on resource 'namespaces/ricc-demos-386214/services/php-amarcord' (or resource may not exist). This command is authenticated as 839850161816@cloudbuild.gserviceaccount.com which is the active account specified by the [core/account] property.

#textPayload: "ERROR: build step 2 "gcr.io/google.com/cloudsdktool/cloud-sdk:slim" failed: step exited with non-zero status: 1"

# Step #2 - "Deploy to DEV version": ERROR: (gcloud.run.deploy) PERMISSION_DENIED:
# Permission 'run.services.get' denied on resource 'namespaces/ricc-demos-386214/services/php-amarcord-cb'
#  (or resource may not exist). This command is authenticated as 839850161816@cloudbuild.gserviceaccount.com
# which is the active account specified by the [core/account] property.
